
package menuutama;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.Koneksi;

/**
 *
 * @author alfar
 */
public class DataPelamar extends javax.swing.JPanel {
    //koneksi mysql 
    private Connection conn = new Koneksi().connect();
    private DialogTambahData dialog = new DialogTambahData(null, true);
    public DefaultTableModel tabmode;
    private String noId;
    
    /**
     * Creates new form NewJPanel
     */
    public DataPelamar() {
        initComponents();
        updateDataTabel();
    }
    
    /**
     * mendapatkan Data Tabel dari database
     */
    protected void updateDataTabel(){
        Object[] Baris = {
            "ID Pelamar",
            "Nama",
            "Jenis Kelamin",
            "No. HP",
            "Alamat",
            "Divisi Dituju"
        };
        
        tabmode = new DefaultTableModel(null, Baris);
        tabelCalonPelamar.setModel(tabmode);

        String sql = "SELECT * FROM calon_pelamar ORDER BY id";
        
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                String a = hasil.getString("id_pelamar");
                String b = hasil.getString("nama");
                String c = hasil.getString("jeniskel");
                String d = hasil.getString("no_hp");
                String e = hasil.getString("alamat");
                String f = hasil.getString("divisi");
                
                String[] data={a, b, c, d, e, f};
                tabmode.addRow(data);
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
    }
    
    /**
     * Mendapatkan Data dari Tabel
     */
    private void getDataTabel(){
        int bar = tabelCalonPelamar.getSelectedRow();
        String a = tabmode.getValueAt(bar, 0).toString();
        String b = tabmode.getValueAt(bar, 1).toString();
        String c = tabmode.getValueAt(bar, 2).toString();
        String d = tabmode.getValueAt(bar, 3).toString();
        String e = tabmode.getValueAt(bar, 4).toString();
        String f = tabmode.getValueAt(bar, 5).toString();        
        
        noId = a;
        dialog.setDataTabel(a, b, c, d, e, f);
    }
    
    protected void hapusDataCalonPelamar(){
        if(noId != null){
            int ok = JOptionPane.showConfirmDialog(null,"hapus","Konfirmasi Dialog",JOptionPane.YES_NO_OPTION);
            if(ok == 0){
                String sql = "DELETE FROM calon_pelamar WHERE id_pelamar='"+noId+"'";
                String sql2 = "DELETE FROM bobot_kandidat WHERE id_pelamar='"+noId+"'";
                String sql3 = "DELETE FROM vektor_s WHERE id_pelamar='"+noId+"'";
                String sql4 = "DELETE FROM vektor_v WHERE id_pelamar='"+noId+"'";
                try{
                    PreparedStatement stat = conn.prepareStatement(sql);
                    PreparedStatement stmt = conn.prepareStatement(sql2);
                    PreparedStatement stnt = conn.prepareStatement(sql3);
                    PreparedStatement stot = conn.prepareStatement(sql4);
                    stat.executeUpdate();
                    stmt.executeUpdate();
                    stnt.executeUpdate();
                    stot.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Data Berhasil diHapus ");
                    updateDataTabel();
                    noId=null;
                }catch(SQLException e){
                    JOptionPane.showMessageDialog(null,"Data Gagal diHapus " + e);
                }
            }
        }else{
            JOptionPane.showMessageDialog(null, "Pilih data yang ingin dihapus! ");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        judul = new javax.swing.JLabel();
        Panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelCalonPelamar = new javax.swing.JTable();
        tombolTambah = new javax.swing.JButton();
        tombolEdit = new javax.swing.JButton();
        tombolHapus = new javax.swing.JButton();
        catatan = new javax.swing.JLabel();

        judul.setBackground(new java.awt.Color(255, 255, 255));
        judul.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        judul.setForeground(new java.awt.Color(0, 51, 153));
        judul.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        judul.setText("  Data Calon Pelamar");
        judul.setOpaque(true);

        Panel.setBackground(new java.awt.Color(255, 255, 255));

        tabelCalonPelamar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No.ID", "Nama", "Jenis Kelamin", "No. HP", "Alamat", "Divisi Dituju"
            }
        ));
        tabelCalonPelamar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelCalonPelamarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelCalonPelamar);

        tombolTambah.setBackground(new java.awt.Color(0, 51, 102));
        tombolTambah.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tombolTambah.setForeground(new java.awt.Color(255, 255, 255));
        tombolTambah.setText("Tambah Data Calon Pelamar");
        tombolTambah.setBorder(null);
        tombolTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolTambahActionPerformed(evt);
            }
        });

        tombolEdit.setBackground(new java.awt.Color(0, 51, 102));
        tombolEdit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tombolEdit.setForeground(new java.awt.Color(255, 255, 255));
        tombolEdit.setText("Edit");
        tombolEdit.setBorder(null);
        tombolEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolEditActionPerformed(evt);
            }
        });

        tombolHapus.setBackground(new java.awt.Color(102, 0, 0));
        tombolHapus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tombolHapus.setForeground(new java.awt.Color(255, 255, 255));
        tombolHapus.setText("Hapus");
        tombolHapus.setBorder(null);
        tombolHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolHapusActionPerformed(evt);
            }
        });

        catatan.setText("Catatan : Edit/Hapus data calon pelamar, klik data pada tabel terlebih dahulu");

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                .addContainerGap(560, Short.MAX_VALUE)
                .addComponent(tombolTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelLayout.createSequentialGroup()
                            .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(catatan)
                                .addGroup(PanelLayout.createSequentialGroup()
                                    .addGap(439, 439, 439)
                                    .addComponent(tombolEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(87, 87, 87)
                                    .addComponent(tombolHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(0, 44, Short.MAX_VALUE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 759, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tombolTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(347, Short.MAX_VALUE))
            .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelLayout.createSequentialGroup()
                    .addGap(61, 61, 61)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(catatan)
                    .addGap(18, 18, 18)
                    .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tombolHapus, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                        .addComponent(tombolEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                    .addGap(0, 45, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(judul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(judul, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(239, 239, 239))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tombolHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolHapusActionPerformed
        // TODO add your handling code here:
        hapusDataCalonPelamar();
    }//GEN-LAST:event_tombolHapusActionPerformed

    private void tombolEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolEditActionPerformed
        // TODO add your handling code here:
        if(noId != null){
            dialog.show();
            updateDataTabel();
            noId=null;
        }else{
            JOptionPane.showMessageDialog(null, "Pilih data yang ingin diUbah! ");
        }
    }//GEN-LAST:event_tombolEditActionPerformed

    private void tombolTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolTambahActionPerformed
        // TODO add your handling code here:
            dialog.kosong();
            dialog.show();
            updateDataTabel();  
            noId=null;
    }//GEN-LAST:event_tombolTambahActionPerformed

    private void tabelCalonPelamarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelCalonPelamarMouseClicked
        // TODO add your handling code here:
        getDataTabel();
    }//GEN-LAST:event_tabelCalonPelamarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JLabel catatan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel judul;
    private javax.swing.JTable tabelCalonPelamar;
    private javax.swing.JButton tombolEdit;
    private javax.swing.JButton tombolHapus;
    private javax.swing.JButton tombolTambah;
    // End of variables declaration//GEN-END:variables
}
