
package menuutama;
//import loginadmin.Login;
import loginadmin.Login;
import com.mysql.jdbc.Connection;
import java.awt.Color;
import java.awt.Cursor;
import java.io.File;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import koneksi.Koneksi;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author alfar
 */
public class MenuUtama extends javax.swing.JFrame {
    Color hoverButton;
    private Connection conn = (Connection) new Koneksi().connect();
    private DialogCetakLaporan dialog = new DialogCetakLaporan(null, true);
    private DialogAdmin dialogAdmin = new DialogAdmin(null, true);
    /**
     * Creates new form NewJFrame
     */
    public MenuUtama() {
        initComponents();
        setVisible(true);
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
        sliderMenuDefault();
        this.hoverButton = lowongan.getBackground();
        Pane.add(Home);
        Pane.repaint();
        Pane.revalidate();
    }
    // untuk sliderMenu
    private void sliderMenuDefault(){
        slideMenuLaporan.setVisible(false);
    }
    
    private void hiddenSubMenu(){
        if(slideMenuLaporan.isVisible() == true){
            slideMenuLaporan.setVisible(false);
        }
    }
    
    private void showSubMenu(JPanel subMenu){
        if(subMenu.isVisible() == false){
            hiddenSubMenu();
            subMenu.setVisible(true);
        }else{
            subMenu.setVisible(false);
        }
    }
    //akhis slider menu
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Home = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        Menu = new javax.swing.JPanel();
        lowongan = new javax.swing.JLabel();
        kriteria = new javax.swing.JLabel();
        slideMenuLaporan = new javax.swing.JPanel();
        laporanCalonPelamar = new javax.swing.JLabel();
        laporanHasilSeleksi = new javax.swing.JLabel();
        laporan = new javax.swing.JLabel();
        penilaian = new javax.swing.JLabel();
        seleksi = new javax.swing.JLabel();
        pelamar = new javax.swing.JLabel();
        judul1 = new javax.swing.JLabel();
        Pane = new javax.swing.JPanel();
        admin = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();

        Home.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Selamat Datang, di Aplikasi");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Sistem Pendukung Keputusan Penerimaan Karyawan Baru WeiTech Indonesia");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Menggunakan Metode WP");

        javax.swing.GroupLayout HomeLayout = new javax.swing.GroupLayout(Home);
        Home.setLayout(HomeLayout);
        HomeLayout.setHorizontalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        HomeLayout.setVerticalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(551, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));

        Menu.setBackground(new java.awt.Color(0, 0, 0));
        Menu.setMaximumSize(new java.awt.Dimension(32767, 600));

        lowongan.setBackground(new java.awt.Color(0, 0, 0));
        lowongan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lowongan.setForeground(new java.awt.Color(255, 255, 255));
        lowongan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lowongan.setText("Data Lowongan");
        lowongan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lowongan.setOpaque(true);
        lowongan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lowonganMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lowonganMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lowonganMouseExited(evt);
            }
        });

        kriteria.setBackground(new java.awt.Color(0, 0, 0));
        kriteria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        kriteria.setForeground(new java.awt.Color(255, 255, 255));
        kriteria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kriteria.setText("Data Kriteria");
        kriteria.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        kriteria.setOpaque(true);
        kriteria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kriteriaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                kriteriaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                kriteriaMouseExited(evt);
            }
        });

        slideMenuLaporan.setBackground(new java.awt.Color(80, 80, 80));
        slideMenuLaporan.setForeground(new java.awt.Color(255, 255, 255));

        laporanCalonPelamar.setBackground(new java.awt.Color(80, 80, 80));
        laporanCalonPelamar.setForeground(new java.awt.Color(255, 255, 255));
        laporanCalonPelamar.setText("    Laporan Data Pelamar");
        laporanCalonPelamar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        laporanCalonPelamar.setOpaque(true);
        laporanCalonPelamar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laporanCalonPelamarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                laporanCalonPelamarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                laporanCalonPelamarMouseExited(evt);
            }
        });

        laporanHasilSeleksi.setBackground(new java.awt.Color(80, 80, 80));
        laporanHasilSeleksi.setForeground(new java.awt.Color(255, 255, 255));
        laporanHasilSeleksi.setText("    Laporan Hasil Seleksi");
        laporanHasilSeleksi.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        laporanHasilSeleksi.setOpaque(true);
        laporanHasilSeleksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laporanHasilSeleksiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                laporanHasilSeleksiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                laporanHasilSeleksiMouseExited(evt);
            }
        });

        javax.swing.GroupLayout slideMenuLaporanLayout = new javax.swing.GroupLayout(slideMenuLaporan);
        slideMenuLaporan.setLayout(slideMenuLaporanLayout);
        slideMenuLaporanLayout.setHorizontalGroup(
            slideMenuLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(laporanCalonPelamar, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
            .addComponent(laporanHasilSeleksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        slideMenuLaporanLayout.setVerticalGroup(
            slideMenuLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slideMenuLaporanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(laporanCalonPelamar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(laporanHasilSeleksi, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        laporan.setBackground(new java.awt.Color(0, 0, 0));
        laporan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        laporan.setForeground(new java.awt.Color(255, 255, 255));
        laporan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        laporan.setText("  Cetak Laporan");
        laporan.setOpaque(true);
        laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laporanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                laporanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                laporanMouseExited(evt);
            }
        });

        penilaian.setBackground(new java.awt.Color(0, 0, 0));
        penilaian.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        penilaian.setForeground(new java.awt.Color(255, 255, 255));
        penilaian.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        penilaian.setText("Data Penilaian");
        penilaian.setOpaque(true);
        penilaian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                penilaianMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                penilaianMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                penilaianMouseExited(evt);
            }
        });

        seleksi.setBackground(new java.awt.Color(0, 0, 0));
        seleksi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        seleksi.setForeground(new java.awt.Color(255, 255, 255));
        seleksi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        seleksi.setText("Data Seleksi");
        seleksi.setOpaque(true);
        seleksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seleksiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                seleksiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                seleksiMouseExited(evt);
            }
        });

        pelamar.setBackground(new java.awt.Color(0, 0, 0));
        pelamar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pelamar.setForeground(new java.awt.Color(255, 255, 255));
        pelamar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pelamar.setText("Data Pelamar");
        pelamar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pelamar.setOpaque(true);
        pelamar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pelamarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pelamarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pelamarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(slideMenuLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lowongan, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                    .addComponent(kriteria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(penilaian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(laporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(seleksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pelamar, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
                .addContainerGap())
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lowongan, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pelamar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kriteria, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(penilaian, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(seleksi, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(laporan, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(slideMenuLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        judul1.setBackground(new java.awt.Color(246, 59, 59));
        judul1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        judul1.setForeground(new java.awt.Color(255, 255, 255));
        judul1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo 100px.png"))); // NOI18N
        judul1.setText("   Sistem Pendukung Keputusan Penerimaan Karyawan Baru WeiTech Indonesia");
        judul1.setAlignmentY(0.0F);
        judul1.setOpaque(true);

        Pane.setBackground(new java.awt.Color(255, 255, 255));
        Pane.setMaximumSize(new java.awt.Dimension(1200, 650));
        Pane.setMinimumSize(new java.awt.Dimension(380, 200));
        Pane.setPreferredSize(new java.awt.Dimension(600, 570));
        Pane.setLayout(new java.awt.CardLayout());

        admin.setBackground(new java.awt.Color(0, 0, 0));
        admin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        admin.setForeground(new java.awt.Color(255, 255, 255));
        admin.setText(" Administrator");
        admin.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        admin.setOpaque(true);
        admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adminMouseExited(evt);
            }
        });

        logout.setBackground(new java.awt.Color(0, 0, 0));
        logout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("  Log Out");
        logout.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        logout.setOpaque(true);
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(judul1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(admin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(judul1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(admin, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Pane, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminMouseExited
        // TODO add your handling code here:
        admin.setBackground(Color.BLACK);
    }//GEN-LAST:event_adminMouseExited

    private void adminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminMouseEntered
        // TODO add your handling code here:
        admin.setBackground(new Color(51,51,51));
        admin.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_adminMouseEntered

    private void adminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminMouseClicked
        // TODO add your handling code here:
//        this.dispose();
//        dialogAdmin.kosong();
        dialogAdmin.show();
    }//GEN-LAST:event_adminMouseClicked

    private void penilaianMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_penilaianMouseExited
        // TODO add your handling code here:
        penilaian.setBackground(hoverButton);
    }//GEN-LAST:event_penilaianMouseExited

    private void penilaianMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_penilaianMouseEntered
        // TODO add your handling code here:
        penilaian.setBackground(new Color(51,51,51));
        penilaian.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_penilaianMouseEntered

    private void penilaianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_penilaianMouseClicked
        // TODO add your handling code here:
        //remove panel
        Pane.removeAll();
        Pane.repaint();
        Pane.revalidate();

        //add Panel, add panel
        Pane.add(new Penilaian());
        Pane.repaint();
        Pane.revalidate();
    }//GEN-LAST:event_penilaianMouseClicked

    private void laporanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanMouseExited
        // TODO add your handling code here:
        laporan.setBackground(hoverButton);
    }//GEN-LAST:event_laporanMouseExited

    private void laporanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanMouseEntered
        // TODO add your handling code here:
        laporan.setBackground(new Color(51,51,51));
        laporan.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_laporanMouseEntered

    private void laporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanMouseClicked
        // TODO add your handling code here:
        showSubMenu(slideMenuLaporan);
    }//GEN-LAST:event_laporanMouseClicked

    private void laporanHasilSeleksiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanHasilSeleksiMouseExited
        // TODO add your handling code here:
        laporanHasilSeleksi.setBackground(new Color(80,80,80));
    }//GEN-LAST:event_laporanHasilSeleksiMouseExited

    private void laporanHasilSeleksiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanHasilSeleksiMouseEntered
        // TODO add your handling code here:
        laporanHasilSeleksi.setBackground(new Color(51,51,51));
        laporanHasilSeleksi.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_laporanHasilSeleksiMouseEntered

    private void laporanHasilSeleksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanHasilSeleksiMouseClicked
        // TODO add your handling code here:
            dialog.kosong();
            dialog.show();
    }//GEN-LAST:event_laporanHasilSeleksiMouseClicked

    private void laporanCalonPelamarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanCalonPelamarMouseExited
        // TODO add your handling code here:
        laporanCalonPelamar.setBackground(new Color(80,80,80));
    }//GEN-LAST:event_laporanCalonPelamarMouseExited

    private void laporanCalonPelamarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanCalonPelamarMouseEntered
        // TODO add your handling code here:
        laporanCalonPelamar.setBackground(new Color(51,51,51));
        laporanCalonPelamar.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_laporanCalonPelamarMouseEntered

    private void laporanCalonPelamarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanCalonPelamarMouseClicked
        // TODO add your handling code here:        
        try{
            String namaFile = "src/laporan/LaporanCalonPelamar.jasper";
//            HashMap parameter = new HashMap();
//            parameter.put("PATH_IMG","src/image/");
            File report_file = new File(namaFile);
            JasperReport jasperReport = (JasperReport) JRLoader.loadObject(report_file.getPath());
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, null, conn);
            JasperViewer.viewReport(jasperPrint, false);
//            JasperViewer.setDefaultLookAndFeelDecorated(true);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_laporanCalonPelamarMouseClicked

    private void kriteriaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kriteriaMouseExited
        // TODO add your handling code here:
        kriteria.setBackground(hoverButton);
    }//GEN-LAST:event_kriteriaMouseExited

    private void kriteriaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kriteriaMouseEntered
        // TODO add your handling code here:
        kriteria.setBackground(new Color(51,51,51));
        kriteria.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_kriteriaMouseEntered

    private void kriteriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kriteriaMouseClicked
        // TODO add your handling code here:
        Pane.removeAll();
        Pane.repaint();
        Pane.revalidate();

        //add Panel, add panel
        Pane.add(new PengaturanKriteria());
        Pane.repaint();
        Pane.revalidate();
    }//GEN-LAST:event_kriteriaMouseClicked

    private void lowonganMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lowonganMouseExited
        // TODO add your handling code here:
        lowongan.setBackground(hoverButton);
    }//GEN-LAST:event_lowonganMouseExited

    private void lowonganMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lowonganMouseEntered
        // TODO add your handling code here:
        lowongan.setBackground(new Color(51,51,51));
        lowongan.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lowonganMouseEntered

    private void lowonganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lowonganMouseClicked
        // TODO add your handling code here:
        //remove panel
        Pane.removeAll();
        Pane.repaint();
        Pane.revalidate();

        //add Panel, add panel 
        Pane.add(new DataLowongan());
        Pane.repaint();
        Pane.revalidate();
    }//GEN-LAST:event_lowonganMouseClicked

    private void seleksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seleksiMouseClicked
        // TODO add your handling code here:
        Pane.removeAll();
        Pane.repaint();
        Pane.revalidate();

        //add Panel, add panel
        Pane.add(new Perhitungan());
        Pane.repaint();
        Pane.revalidate();
    }//GEN-LAST:event_seleksiMouseClicked

    private void seleksiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seleksiMouseEntered
        // TODO add your handling code here:
        seleksi.setBackground(new Color(51,51,51));
        seleksi.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_seleksiMouseEntered

    private void seleksiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seleksiMouseExited
        // TODO add your handling code here:
        seleksi.setBackground(hoverButton);
    }//GEN-LAST:event_seleksiMouseExited

    private void pelamarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pelamarMouseClicked
        // TODO add your handling code here:
        Pane.removeAll();
        Pane.repaint();
        Pane.revalidate();

        //add Panel, add panel 
        Pane.add(new DataPelamar());
        Pane.repaint();
        Pane.revalidate();
    }//GEN-LAST:event_pelamarMouseClicked

    private void pelamarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pelamarMouseEntered
        // TODO add your handling code here:
        pelamar.setBackground(new Color(51,51,51));
        pelamar.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_pelamarMouseEntered

    private void pelamarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pelamarMouseExited
        // TODO add your handling code here:
        pelamar.setBackground(hoverButton);
    }//GEN-LAST:event_pelamarMouseExited

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_logoutMouseClicked

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        // TODO add your handling code here:
        logout.setBackground(new Color(51,51,51));
        logout.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
        // TODO add your handling code here:
        logout.setBackground(hoverButton);
    }//GEN-LAST:event_logoutMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Home;
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel Pane;
    private javax.swing.JLabel admin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel judul1;
    private javax.swing.JLabel kriteria;
    private javax.swing.JLabel laporan;
    private javax.swing.JLabel laporanCalonPelamar;
    private javax.swing.JLabel laporanHasilSeleksi;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel lowongan;
    private javax.swing.JLabel pelamar;
    private javax.swing.JLabel penilaian;
    private javax.swing.JLabel seleksi;
    private javax.swing.JPanel slideMenuLaporan;
    // End of variables declaration//GEN-END:variables
}
